version: '3.8'
services:
  spring-boot-app:
    image: mustapha69/spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
